apply plugin: 'war'


tasks.withType(War).configureEach{
	if (!archiveFileName.get().contains('plain')) {
		destinationDirectory = file("$rootDir/build/distributions")
	}
}

bootJar{
    enabled = false
}
bootRun{
    enabled = false

    String activeProfile = System.properties['spring.profiles.active']
    systemProperty "spring.profiles.active", activeProfile
}

dependencies {
    implementation fileTree(dir: '../libs', includes: ['*.jar'])
    implementation project(':ghlove-common')
    println '[ghlove-api]>>>>>>>>>>> [active]=' + project.hasProperty("active")
    if (!project.hasProperty("active") || 'local'.equals(project.property("active"))) {
    	implementation 'org.springframework.boot:spring-boot-starter-web'
    } else {
	    implementation ('org.springframework.boot:spring-boot-starter-web') {
	        exclude module: 'spring-boot-starter-tomcat'
	    }

	    implementation 'org.springframework.boot:spring-boot-starter-undertow'
	    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	}
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.google.code.gson:gson:2.8.7'

    implementation 'org.hibernate:hibernate-validator:7.0.1.Final'

    // Jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.10.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.10.5',
            'io.jsonwebtoken:jjwt-jackson:0.10.5'

}

task copyOnePassProperties {
	doLast{
		def profile = project.hasProperty('active') ? project.active : 'local'
		def srcFile = file("src/main/resources/onepass-${profile}.properties")
		def dstFile = file("src/main/resources/onepass.properties")

		if ( srcFile.exists()) {
			dstFile.text = srcFile.text
			println "1Copied onepass-${profile}.properties -> onepass.properties"
		}else{
			thorw new GradleException("2onepass-${profile}.properties not found")
		}
	}
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    dependsOn(copyOnePassProperties)
    doLast {
    	def dstFile = file("src/main/resources/onepass.properties")
    	def srcFile = file("src/main/resources/onepass-local.properties")

    	if ( srcFile.exists()) {
			dstFile.text = srcFile.text
			println "3Copied onepass-local.properties -> onepass.properties"
		}else{
			thorw new GradleException("4onepass-local.properties not found")
		}

    }
}
