# [SalesOn 환경 설정 - DEV]
# 서버별로 구별되지 않는 공통 항목을 설정함. (경로가 다른 부분은 제외함)
#

#######################
# SalesOn
#######################
saleson:
  version: "3.15.0"
  root: "/home/ghlove"
  storage-root: ${saleson.root}/backoffice/static
  static-root: ${saleson.root}/backoffice/static
  file-root: ${saleson.root}    # licence, payment 등의 경로 기준을 서버 환경에 변경하여 사용함.
  license-root: ${saleson.root}

  # License
  license:
    clientid: icraft
    creation.date: 20230719152530
    hash.key: f7ed568324b16b6a9da30c60aefccfaee4b553afcd3707cf62aa78d1d6c8c3ce
    file: ${saleson.license-root}/license/icraft-20230719152530.license
    key: ${saleson.license-root}/license/icraft-20230719152530.key
    healthcheck.uri: /healthcheck

  # Batch 실행 여부
  batch: false


  # DB Vendor
  database:
    vendor: cubrid
    dialect: org.hibernate.dialect.CUBRIDDialect
    hbm2ddl: update

  # datasource
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    #jdbc-url: jdbc:cubrid:192.168.100.251:33000:ghlove:::?charset=UTF-8
    jdbc-url: jdbc:cubrid:192.168.84.58:34000:ghlove2:::?charset=UTF-8
    username: dba
    password: rhgidtkfkd!1234A
    connection-test-query: SELECT 1
    minimum-idle: 10
    maximum-pool-size: 10
    pool-name: pool-saleson
    data-source-properties:
      rewriteBatchedStatements: true

  # 서비스 DOMAIN
  url:
    shoppingmall: http://152.99.104.8
    bo: http://152.99.104.8
    api: http://152.99.104.8
    frontend: http://152.99.104.8
    cdn:

  # API Allow Origin
  # '*' or 'http://front.saleson.com' or 'http://front1.saleson.com,http://front2.saleson.com'
  api:
    crossorigins: http://localhost:3000

  # Logging
  log.path: ${saleson.file-root}/logs

  # Mail
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: xxxx@gmail.com
    password: password
    smtp:
      start-tls-enable: true
      auth: true

  # Manager Access Port Settings.. (If the value is blank,system does not check the connection port.)
  opmanager.access.port:

  # DB Query Log Intercepter (Y/N)
  query.log: "N"

  # Shopping Mall Type (1: NORMAL, 2: MALL IN MALL - 입점 몰인몰)
  mall.type: 2

  # 서비스 VIEW MODE (api/jsp)
  view.type: api

  # Mobile Prefix
  # saleson.mobile.prefix: /sp
  mobile.prefix: /m

  # No Image Path
  noimage.path: /content/images/common/no-image-gray.gif

  # 관리자 본인 인증 (시간은 초)
  auth:
    manager:
      process: false
      time: 3600


email:
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    jdbc-url: jdbc:cubrid:192.168.84.58:34000:ems:::?charset=UTF-8
    username: dba
    password: rhgidtkfkd!1234A
    connection-test-query: SELECT 1
    minimum-idle: 10
    maximum-pool-size: 10

slave:
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    jdbc-url: jdbc:cubrid:192.168.84.58:34000:ghlove2:::?charset=UTF-8
    username: dba
    password: rhgidtkfkd!1234A
    connection-test-query: SELECT 1
    minimum-idle: 10
    maximum-pool-size: 10

analysis:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:cubrid:192.168.84.58:34000:ghlove2:::?charset=UTF-8
    username: dba
    password: rhgidtkfkd!1234A
    connection-test-query: SELECT 1
    minimum-idle: 10
    maximum-pool-size: 10
    
nhapi:
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    jdbc-url: jdbc:cubrid:192.168.84.58:34000:ghlove_api:::?charset=UTF-8
    username: dba
    password: rhgidtkfkd!1234A
    connection-test-query: SELECT 1
    minimum-idle: 10
    maximum-pool-size: 10

# Log DataSource
log:
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    jdbc-url: jdbc:cubrid:192.168.84.58:30000:ICRAFT:::?charset=UTF-8
    username: dba
    # password: Dnlvldk123#
    password: rhgidtkfkd!1234A
    connection-test-query: SELECT 1
    minimum-idle: 10
    maximum-pool-size: 10
    pool-name: pool-log


#######################
# SalesOn - Etc
#######################
file.storage:
  # local, azure, aws
  type: local
  azure:
    accountName: ""
    accountKey: ""
  aws:
    accessKey: ""
    secretKey: ""
    bucketName: ""

# 업로드 root (파일정보 저장 시 /abc/ef/g.jpg 형태로 저장된 경우 물리적 위치 기준 - 마이그레이션 시 경로까지 저장한 경우 사용)
upload:
  root: ${saleson.storage-root}

  # 업로드 경로 (browser 접속 시 시작경로)
  base.folder: /upload

  # 업로드 경로 - 물리적 저장 경로 (absolute path)
  save.folder: ${saleson.storage-root}/upload

  # 파일명 저장 방식 (1:원본파일명, 2:파일 키로 변환)
  option.save.filename: 2


# Resource Location
resource:
  static.location: file:${saleson.static-root}
  storage.location: file:${saleson.storage-root}

  # Resources Folders
  request.uris: /content,/upload


# Security
security:
  # 양방향 암호화 키
  cryptor.key: "4646A6A7B2E0A5CE40F063A3347AF084"

  # XSS FILTER EXCLUDE Parameters (,)
  xss.filter.exclude.parameters: buyerContent,adminContent,content,tagOverturue,tagAdwords,editContent,categoryFooter,categoryHeader,userHtmlEdit,brandContent,headerContent,agreement,protectPolicy,deliveryInfo,featuredContent,featuredSimpleContent,detailContent,detailContentMobile

  # Security (yes/no)
  opmanager.allow_ip_check: "no"

  # Security Port Mapping (context-security.xml)
  # 1. http, https \uB85C\uB9CC \uAD6C\uBD84\uB418\uB294 \uACBD\uC6B0 80, 80
  # 2. http, https://xxx:8443 \uC778 \uACBD\uC6B0 80, 8443
  port:
    http: 8080
    https: 8080

# Board Config
board:
  data.table: SHOP


#######################
# UMS
#######################
ums:
    client-id: onlinepowers
    callback: 02-6737-9200
    grp.cd: "01003"     # UMS 정산 그룹코드 (개발:01003, 운영:01002)
  
    calculate:
      host: msg.safeon.com
      port: 7180
      path: /sms.server/calculate.do
  
    # 발송서버
    api:
      secret: 613690CD913C7E69998DD12DF14XXXX
      url: http://ums.onlinepowers.com
  
    # Alimtalk
    kakao:
      alimtalk:
        host: msg.safeon.com
        host.port: 47201
        mplaceid: micesoftat01
        senderkey: 08bc4c4c84e3af0f64172c5f46b7f954d5d4XXXX
        if-url: http://192.168.239.25:8088/api/sendAlimtalk
  
    # MMS IMAGE
    mms:
      image.upload:
        host: msg.safeon.com
        port: 7180
        path: /sms.server/mms_save.do
  
    # PUSH
    push:
      test: "N"
      
    # Nuri2
    nuri2:
      sender-key : a543484a1dbc03bc9723ad4c2f6633761fcdcb0b



#######################
# Payment
#######################
pg:
  service:

  cj:
    mid: CJ1401070001
    card.pay.url: http://210.122.96.190/SmartPayment/SmartPayCreditcard.aspx
    vbank.pay.url: http://210.122.96.190/SmartPayment/SmartPayVirtualAccount.aspx
    realtimebank.pay.url: http://210.122.96.190/SmartPayment/SmartPayAccount.aspx
    card.cancel.url: http://210.122.96.190/Pay/PayCancel.aspx
    #card.pay.url: https://pay.cjsystems.co.kr/SmartPayment/SmartPayCreditcard.aspx

  # PG - inipay
  inipay:
    home: ${saleson.file-root}/payment/INIpay50
    web.type: webStandard
    mid: INIpayTest
    escrow.mid: iniescrow0
    keypass: 1111
    escrow.keypass: 1111
    mobile.keypass: 1111
    mobile.mid: INIpayTest
    sign.key: SU5JTElURV9UUklQTEVERVNfS0VZU1RS

  # PG - KSPAY
  kspay:
    mid: 2999199999
    addr: localhost
    port: 29991
    url: "https://kspay.ksnet.to/store/KSPayFlashV1.3/KSPayPWeb.jsp?sndCharSet=utf-8"
    mbUrl: https://kspay.ksnet.to/store/mb2/KSPayPWeb_utf8.jsp

  # PG - LGDACOM
  lgdacom:
    serviceType: test
    home: ${saleson.file-root}/payment/lgdacom
    mid: tosspayments
    key: b495c00ba8fcd62b18d69870c2c26979
    viewType: iframe
    realtimePartcancelFlag: N
    hpPartcancelFlag: Y

  # PG - NHN KCP
  kcp:
    module.type: 01
    quotaopt: 12
    currency: 410
    g.conf:
      home.dir: ${saleson.file-root}/payment/kcp
      #key.dir: ${saleson.file-root}/payment/kcp/bin/pub.key
      log.dir: ${saleson.file-root}/logs
      gw.url: testpaygw.kcp.co.kr

      # 결제창 호출 url
      hub.js.url: "https://testpay.kcp.co.kr/plugin/cross_service/payplus_hub_web.js?1=29"
      web.js.url: https://testpay.kcp.co.kr/plugin/payplus_web.jsp
      mobile.js.url: /content/mobile/js/approval_key.js

      server: false
      #site.cd: T0000
      #site.key: 3grptw1.zW0GSo4PQdaGvsF__
      site.cd: T0007
      site.key: 4Ho4YsuOZlLXUZUdOxM1Q7X__
      site.name: ESCROW TEST SHOP
      gw.port: 8090
      log.level: 3
      tx.mode: 0

      # 현금영수증 발행 관련 설정
      tax.no: 0000000000
      corp.addr: 서울시 구로구 구로동 170-5
      corp.owner: 홍길동
      corp.tel: 02-0000-1111


  # PG - EasyPay 8.0
  easypay:
    g.conf:
      site.name: TEST SHOP
      site.cd: T0009379
      gw.url: testgw.easypay.co.kr
      # site.cd: T0002013
      # gw.url: gw.easypay.co.kr real

      gw.port: 80
      log.level: 1
      key.dir: ${saleson.file-root}/payment/easypay/cert
      log.dir: ${saleson.file-root}/logs
      test.js.url: https://testpg.easypay.co.kr/webpay/EasypayCard_Web.js
      real.js.url: https://pg.easypay.co.kr/webpay/EasypayCard_Web.js
      viewType: iframe

# Nicepay
nicepay:
  socket.flag: Y
  charset: utf-8
  encoding.parameters: CardNo,CardExpire,CardPwd
  log.path: ${saleson.file-root}/logs

# Payco
payco:
  seller.key: S0FSJE
  seller.cpId: PARTNERTEST
  order.api.url: https://alpha-api-bill.payco.com

# Kakaopay
kakaopay:
  mid: cnstest25m
  encode.key: "33F49GnCMS1mFYlGXisbUDzVf2ATWCl9k3R++d5hDd3Frmuos/XLx8XhXpe+LDYAbpGKZYSwtlyyLOtS/8aD7A=="
  merchant.enc.key: 10a3189211e1dfc6
  merchant.hash.key: 10a3189211e1dfc6
  cnspay.path: ${saleson.file-root}/payment/kakaopay/properties
  log.path: ${saleson.file-root}/logs
  web.path: https://kmpay.lgcns.com:8443/
  msg.name: merchant/requestDealApprove.dev


# NaverPay
naver:
  checkout:
    order.api.url: https://test-checkout.naver.com/customer/api/order.nhn
    pc.payUrl: https://test-checkout.naver.com/customer/order.nhn
    mobile.payUrl: https://test-m.checkout.naver.com/mobile/customer/order.nhn
    wishlist.api.url: https://test-checkout.naver.com/customer/api/wishlist.nhn
    pc.wishlist: https://test-checkout.naver.com/customer/wishlistPopup.nhn
    mobile.wishlist: https://test-m.checkout.naver.com/mobile/customer/wishList.nhn
    pc.button.script: http://test-checkout.naver.com/customer/js/checkoutButton2.js
    mobile.button.script: http://test-checkout.naver.com/customer/js/mobile/checkoutButton.js

  # Naverpay (결제형)
  pay:
    api.url: https://dev.apis.naver.com


# PopBill
popbill:
  corp.num:
  user.id:
  link.id:
  secret.key:
  # 운영설정으로 변경할때 true -> false로 변경
  is.test: true

cashbill:
  service:


#######################
# SNS로그인
#######################
# Naver
naver.login:
  appId: HEGPL8jkr8mQEVWjekMw
  callback: /sns-user/naver-callback

# Kakao
kakao.login.appId: 2ad2a946a7b2476be7ba05450ca77e4f

# Facebook
fb.login.appId: 2235149073448625



#######################
# 본인인증
#######################
user:
  auth:
    #휴대폰 인증
    pcc:
      service: siren24
      mid:
      front.serviceNo:
      mobile.serviceNo:

    # IPIN 인증
    ipin:
      service: siren24
      mid:
      front.serviceNo:
      mobile.serviceNo:



#######################
# Application
#######################
# User Agent
app:
  user.agent:
    ios: SALESON_APPLICATION_IOS
    android: SALESON_APPLICATION_ANDROID


#######################
# Server
#######################
server:
  port: 8080
  ajp:
    protocol: AJP/1.3
    port: 8009
    enabled: false
  ssl:
    enabled: false
    key-store: ${saleson.file-root}/keystore/saleson.keystore
    key-store-password: 111111

  error:
    whitelabel.enabled: false
    include-stacktrace: NEVER

  servlet:
    context-parameters.defaultHtmlEscape: false

  tomcat:
    additional-tld-skip-patterns: "*mchange-commons-java*.jar"
    basedir: ${saleson.file-root}/temp

  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      force-request: true
      charset: UTF-8
      enabled: true
      force: true



#######################
# Spring
#######################
spring:
  main.allow-bean-definition-overriding: true
  security.filter.order: 100
  output.ansi.enabled: NEVER
  jackson:
    serialization:
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization.fail-on-unknown-properties: false
  devtools:
    livereload.enabled: false
    restart.enabled: false
  thymeleaf.cache: false
  aop.auto: true      # enables AOP using @EnableAspectJAutoProxy annotation
  pid.file: saleson.pid
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


#######################
# Logging Level
#######################
logging:
  level:
    log4jdbc.log4j2: ERROR
    jdbc:
      connection: OFF
      sqlonly: OFF
      audit: OFF
      resultset: OFF
      sqltiming: DEBUG
      resultsettable: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    com.onlinepowers: INFO
    com.onlinepowers.framework.web.interceptor.WebLogInterceptor: TRACE
    saleson.common.config.LogDaoAspect: TRACE
    saleson.common.config.LogSvcAspect: TRACE
    saleson: INFO
    
# Outside Connection
outconn:
  # administration net
  admin-addressinfo-url: http://192.168.84.55:4143/api/mopas/rsgstadresinfo
  # juso search api
  juso-api:
    url: http://www.juso.go.kr/addrlink/addrLinkApiJsonp.do
    key: U01TX0FVVEgyMDIyMTEyNTE0MTUzMTExMzI1OTc=
  # korea receipt api
  korea-api:
    loginIp: 152.99.104.11
    loginUrl: https://192.168.239.18:4141/jwtLoginAction.do
    actionUrl: https://192.168.239.18:4141/jwtAction.do?actionId=ATESFACA001C11
    #loginUrl: https://116.67.103.158/jwtLoginAction.do
    #actionUrl: https://116.67.103.158/jwtAction.do?actionId=ATESFACA001C11
    key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/RzW8TWg9hB7T1BWFSrwAASoNt/tBjTYWojvo3gB5MRjx+TI+tI7BqmhhxjAPv3mDNjBgeCW/J5UsCdYOt/dDyYyGiXjHSTE+JsX6Z1i3soDJJzwGnYLbRpbAb9mUi75T0Imwa4P4TLMHFzjw7r57MvJd26RKJnJe0IPGBK0CcQIDAQAB
    id : ilovegohyang
    password : rhgid#rlqn
    
  # seoul buga regist
  seoul-buga-url: http://192.168.84.55:4142/api/seoul/epaymentno
  # seoul sunap search
  seoul-sunap-url: http://192.168.84.55:4141/api/etax/getSunapStatus
  # contry(now) buga regist
  contry-now-buga-url: http://192.168.84.55:4142/api/curgnr/epaymentno
  # contry(now) sunap search
  
  contry-now-sunap-url: http://192.168.84.55:4142/api/curgnr/receipt
  # giro
  giro-url: https://www.giro.or.kr/epay/hometown/index.do
  # AES256 key
  giro-aes256-key: rhgidtkfkdrmarufdnjswlfhdusrP!@#
  # AES256 iv
  giro-aes256-iv: rhgidtkfkdrmaruf
  # 내부 연계 URL1 - nginternal
  in-link-url: https://192.168.84.55:4145
  
  
#######################
# Sms
#######################
sms:
  #. 국민비서
  ips:
    svcGrpId: "812"
    prvcIdntfcSeCd: C0090001
    esbIfId: IF_P01_MIS_IPS_ALM08
    
######금융인증서#######
fincert:
  #url: https://certapi.yeskey.or.kr/oauth/2.0/api/token
  #ucpidUrl: https://certapi.yeskey.or.kr/v1/ucpid/ucpid-info
  url: https://192.168.239.18:4141/oauth/2.0/api/token
  ucpidUrl:  https://192.168.239.18:4141/v1/ucpid/ucpid-info
  client-id: ea1525f5-f619-4398-abc2-2c6d9581550d
  client-secret: 8a6aa6d9-47d9-4999-9dd5-8f4a36d1b526
  scope: ucpid
  grant-type: client_credentials
  server-id: server_ilovegohyang
  cp-code: Y30000001301


# 답례품 관리자 비밀번호/인증서 암호화 용 값, 변경시 답례품 관리자 비밀번호 전체 초기화 필요
salt:
  strForSellerSalt: MOIS2023
  #adminPwd: 고향사랑1!
  adminPwd: rhgidtkfkd1!
  adminPwd2 : 1234t
  
#######################
# TotalSearch Engine
#######################
totalsearch-server:
  engine-url: 192.168.100.248:7577
  ksf-url: 192.168.100.248:7614
  
ems:
  host: http://192.168.100.250:8380/api/sendMail.do
  send:
    username: 고향사랑e음
    email: webmatser@ilovegohyang.go.kr 

pkiSellerLoginDate : "21241231"

jsVersion : "202508121640"


kakao:
  # toolkit : 카카오 인증 전용 툴킷
  toolkit-url: http://192.168.239.25:22000
  # toolkit2: 카카오 + 네이버 인증 툴킷
  toolkit-url2: http://192.168.239.25:22000
  # 토큰 받기 - 미사용(연결안됨)
  token-url: https://kauth.kakao.com/oauth/token
  # 전자서명 검증 - 미사용(연결안됨)
  sign-check-url: https://cert-sign.kakao.com/sign/v2/verify
  # api 주소 => 외부연계서버 proxy
  # api-url: https://kapi.kakao.com
  api-url: http://192.168.239.18:4141
  # 앱 rest api 키
  rest-api-key: 4d3102cb9b8bcc39d0965d90c801c749
  # 앱 admin 키
  app-admin-key:  bc1a00e2d9f31b5d789b93e3bb2b0162
  # redirect uri
  redirect-uri: ${saleson.url.frontend}/users/login.html
  # redirect uri2
  redirect-uri2: ${saleson.url.frontend}/users/join.html
  # toolkit access token
  access-token: 6fc5000616806625c5c1457f0f4260b086e8542c5f0947001308b02c

next :
  buga-request-url: https://192.168.84.55:4145/api/nextgnr/send
  sunap-info-request-url: https://192.168.84.55:4145/api/nextgnr/sunapInfoConfirm
  
######검색엔진 ADDR#####
integration :
  env : dev
#  운영 검색엔진 URL - 개발에서는 로컬에 설치된 검색엔진 서버에 접근이 불가함
#  해당 문제 해결되지 않을 경우, 개발은 AS-IS의 XML 답례품 조회를 따라야 함
  search-engine-url : http://192.168.84.13:7577/search?
  
######Smart Delivery API#####
sweettracker :
  url : https://192.168.239.25:4141/api/v1/trackingInfo
  api_key : PMaE5cCO8dcNxr5ZdCxSIA
  
######NetFunnel Env#####
NetFunnel :
  env : dev