package saleson.common.security.masking;

public enum Masking {
	ID, NAME, BANK_ACCOUNT, PHONE_NUMBER, TEL_NUMBER, ADDRESS, ADDRESS_DETAIL, ZIPCODE, NEW_ZIPCODE, EMAIL, IP, BIRTHDAY, GH_ADDRESS, GH_PHONE_NUMBER, GH_EMAIL;
}
